pull_request_title: 'chore: new crowdin updates'
commit_message: 'locale(%language%): new translations for %original_file_name%'
append_commit_message: false
files:
  - source: /src/ru/**/*.json
    translation: /src/%two_letters_code%/**/%original_file_name%
